services:
  ollama:
    image: ollama/ollama:0.3.13
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"

